export type HistorianManager={memberId:string;teamName:string;publicName:string|null;championships:number;wins:number;losses:number;ties:number;winPercentage:number|null;playoffAppearances:number;playoffWins:number;playoffLosses:number;playoffWinPercentage:number|null;pointsFor:number};
export type HistorianChampion={year:number;memberId:string;teamName:string;publicName:string|null;runnerUp:string;score:number;runnerUpScore:number};
export type HistorianRivalry={memberAId:string;memberBId:string;memberATeamName:string;memberBTeamName:string;memberAPublicName:string|null;memberBPublicName:string|null;games:number;memberAWins:number;memberBWins:number;ties:number};
export type HistorianRecord={type:string;rank:number;year:number;week:number;memberId:string;teamName:string;publicName:string|null;opponent:string;value:number};
export type HistorianSeason={year:number;memberId:string;teamName:string;wins:number;losses:number;ties:number;pointsFor:number;finalStanding:number|null};
export type HistorianCorpus={managers:HistorianManager[];champions:HistorianChampion[];rivalries:HistorianRivalry[];records:HistorianRecord[];seasons:HistorianSeason[]};
export type HistorianResponse={answer:string;facts:string[];href?:string;hrefLabel?:string};

const pct=(value:number|null)=>value===null?"—":`${(value*100).toFixed(1)}%`;
const record=(wins:number,losses:number,ties:number)=>`${wins}-${losses}${ties?`-${ties}`:""}`;
const includesPhrase=(question:string,value:string|null|undefined)=>Boolean(value&&value.length>1&&question.includes(value.toLowerCase()));

function mentionedManagers(question:string,corpus:HistorianCorpus){
  return corpus.managers.filter(manager=>includesPhrase(question,manager.publicName)||includesPhrase(question,manager.teamName)||corpus.seasons.some(season=>season.memberId===manager.memberId&&includesPhrase(question,season.teamName)));
}

export function answerHistorian(rawQuestion:string,corpus:HistorianCorpus):HistorianResponse {
  const q=rawQuestion.toLowerCase().replace(/[^a-z0-9% ]/g," ").replace(/\s+/g," ").trim();
  const year=Number(q.match(/\b20(?:1[7-9]|2[0-6])\b/)?.[0])||null; const mentioned=mentionedManagers(q,corpus);
  const asksRivalry=/rival|head to head|h2h|versus| vs |against/.test(` ${q} `);
  if(mentioned.length>=2&&asksRivalry){const [a,b]=mentioned;const rivalry=corpus.rivalries.find(r=>(r.memberAId===a.memberId&&r.memberBId===b.memberId)||(r.memberAId===b.memberId&&r.memberBId===a.memberId));if(rivalry){const aWins=rivalry.memberAId===a.memberId?rivalry.memberAWins:rivalry.memberBWins;const bWins=rivalry.memberAId===b.memberId?rivalry.memberAWins:rivalry.memberBWins;const leader=aWins===bWins?"The series is tied.":`${aWins>bWins?a.teamName:b.teamName} leads the series.`;return {answer:`${a.teamName} is ${aWins}-${bWins}${rivalry.ties?`-${rivalry.ties}`:""} against ${b.teamName} across ${rivalry.games} meetings. ${leader}`,facts:[`${a.publicName??a.teamName}: ${aWins} wins`,`${b.publicName??b.teamName}: ${bWins} wins`,`${rivalry.ties} ties`],href:"/museum/rivalries",hrefLabel:"Open the rivalry room"};}}
  if(/champion|championship|title|won the league|who won|winner|rings?/.test(q)){
    if(year){const champion=corpus.champions.find(c=>c.year===year);return champion?{answer:`${champion.teamName} won the ${year} JBL championship, defeating ${champion.runnerUp} ${champion.score.toFixed(2)}–${champion.runnerUpScore.toFixed(2)}.`,facts:[champion.publicName??champion.teamName,`${champion.score.toFixed(2)} championship points`],href:"/museum/playoffs",hrefLabel:"View the playoff museum"}:{answer:`The ${year} champion is not yet recorded as final.`,facts:["The historian reports only completed championship matchups."],href:"/museum/seasons",hrefLabel:"Open the season archive"};}
    if(mentioned[0]){const manager=mentioned[0];const titles=corpus.champions.filter(c=>c.memberId===manager.memberId);return {answer:titles.length?`${manager.teamName} has ${titles.length} JBL championship${titles.length===1?"":"s"}: ${titles.map(t=>t.year).join(", ")}.`:`${manager.teamName} has not won a recorded JBL championship.`,facts:[`${manager.championships} career titles`,`${manager.playoffAppearances} playoff appearances`],href:`/museum/managers/${manager.memberId}`,hrefLabel:"Open the career exhibit"};}
    const leader=[...corpus.managers].sort((a,b)=>b.championships-a.championships||Number(b.winPercentage)-Number(a.winPercentage))[0];return {answer:`${leader.teamName} leads JBL history with ${leader.championships} championship${leader.championships===1?"":"s"}.`,facts:[`${leader.publicName??leader.teamName}`,`${pct(leader.winPercentage)} career win rate`],href:"/museum/managers",hrefLabel:"View manager rankings"};
  }
  if(/highest|most points|best score|scoring record/.test(q)){const top=corpus.records.find(r=>r.type==="highest_score"&&r.rank===1);if(top)return {answer:`The highest true single-week score is ${top.value.toFixed(2)} by ${top.teamName} in Week ${top.week} of ${top.year}, against ${top.opponent}.`,facts:[top.publicName??top.teamName,"Multi-week aggregates excluded"],href:"/museum/records",hrefLabel:"Open the record book"};}
  if(/lowest|fewest points|worst score|scoring basement/.test(q)){const low=corpus.records.find(r=>r.type==="lowest_score"&&r.rank===1);if(low)return {answer:`The lowest recorded single-week score is ${low.value.toFixed(2)} by ${low.teamName} in Week ${low.week} of ${low.year}, against ${low.opponent}.`,facts:[low.publicName??low.teamName,"Multi-week aggregates excluded"],href:"/museum/records",hrefLabel:"Open the record book"};}
  if(/best win|highest win|win percentage|win rate|best manager|greatest manager/.test(q)){const leader=[...corpus.managers].filter(m=>m.winPercentage!==null).sort((a,b)=>Number(b.winPercentage)-Number(a.winPercentage))[0];return {answer:`${leader.teamName} owns the best career regular-season win percentage at ${pct(leader.winPercentage)}, with a ${record(leader.wins,leader.losses,leader.ties)} record.`,facts:[`${leader.championships} championships`,`${leader.playoffAppearances} playoff appearances`],href:`/museum/managers/${leader.memberId}`,hrefLabel:"Open the career exhibit"};}
  if(year&&/standing|season|record|best team|first place/.test(q)){const rows=corpus.seasons.filter(s=>s.year===year).sort((a,b)=>(a.finalStanding??99)-(b.finalStanding??99));const top=rows[0];if(top)return {answer:`${top.teamName} finished first in ${year} at ${record(top.wins,top.losses,top.ties)} with ${top.pointsFor.toFixed(1)} points scored.`,facts:[`${rows.length} teams recorded`,top.finalStanding===1?"Official final standing: 1":"Season still in progress"],href:`/museum/seasons/${year}`,hrefLabel:`Browse ${year}`};}
  if(mentioned[0]){const manager=mentioned[0];if(/playoff/.test(q))return {answer:`${manager.teamName} has made the playoffs ${manager.playoffAppearances} times and is ${manager.playoffWins}-${manager.playoffLosses} in recorded playoff games (${pct(manager.playoffWinPercentage)}).`,facts:[`${manager.championships} championships`,`${pct(manager.winPercentage)} regular-season win rate`],href:`/museum/managers/${manager.memberId}`,hrefLabel:"Open the career exhibit"};return {answer:`${manager.teamName} is ${record(manager.wins,manager.losses,manager.ties)} all-time with a ${pct(manager.winPercentage)} regular-season win rate, ${manager.championships} championship${manager.championships===1?"":"s"}, and ${manager.playoffAppearances} playoff appearances.`,facts:[`${manager.pointsFor.toFixed(1)} career regular-season points`,`${manager.playoffWins}-${manager.playoffLosses} playoff record`],href:`/museum/managers/${manager.memberId}`,hrefLabel:"Open the career exhibit"};}
  return {answer:"I can answer grounded questions about championships, manager records, win percentages, playoff résumés, rivalries, season standings, and weekly scoring records. Name a manager, team, rival pair, or season to narrow the result.",facts:["Try: Who won in 2021?","Try: What is Foz's career record?","Try: Who has the highest weekly score?"]};
}
