import Link from "next/link";
import { ExhibitHeader } from "@/components/exhibit-header";
import { getDraftHistory } from "@/lib/data/museum";

export default async function DraftsPage() {
  const drafts=await getDraftHistory(); const years=[...new Set(drafts.map(r=>r.year))];
  return <main className="exhibit-page"><ExhibitHeader eyebrow="The draft vault" title="Draft history" description="Preserved ESPN draft entries by season and team. Offline entries document recorded players; they do not establish the actual snake order or auction price." />
    <div className="coverage-notice"><strong>Draft entries and Week 1 rosters are different records</strong><p>Week 1 lineups may include trades, waivers, and free-agent moves made after the draft. They are not verified pre-transaction rosters. Auction prices are unavailable when ESPN did not preserve them; zero bid values are not treated as free purchases.</p></div>
    <div className="season-stack">{years.map((year,index)=>{const yearPicks=drafts.filter(r=>r.year===year); const teams=[...new Set(yearPicks.map(r=>r.member_id))]; const draftType=yearPicks[0]?.draft_type; return <details className="season-card" key={year} open={index===0}><summary><span><strong>{year}</strong><small>{draftType==="OFFLINE"?"Offline entries · original format unverified":`${draftType} draft`}</small></span><span>{yearPicks.length} selections · {teams.length} teams</span><i>+</i></summary><div className="season-body"><p>{draftType==="OFFLINE"?"Numbers below are ESPN entry numbers, not verified live draft order.":"Round and pick numbers are preserved from ESPN."} {year>=2019?<Link href={`/museum/seasons/${year}#week-1`}>Browse Week 1 matchups and rosters →</Link>:"Player-level Week 1 rosters are unavailable before 2019."}</p><div className="draft-team-grid">{teams.map(team=>{const picks=yearPicks.filter(r=>r.member_id===team); return <article className="draft-team" key={team}><header><div><h3>{picks[0]?.team_name}</h3><small className="owner-label">{picks[0]?.public_name}</small></div><span>{picks.length} picks</span></header><ol>{picks.map(pick=><li key={pick.overall_pick_number}><span>{pick.overall_pick_number}</span><div><strong>{pick.player_name?.startsWith("ESPN Player ")?"Player unavailable":pick.player_name}</strong><small>{pick.default_position||"—"}{pick.pro_team?` · ${pick.pro_team}`:""}</small></div><b>{draftType==="OFFLINE"?`Entry ${pick.overall_pick_number}`:`R${pick.round_number} · P${pick.round_pick_number}`}{Number(pick.bid_amount)>0?` · $${Number(pick.bid_amount).toFixed(0)}`:""}</b></li>)}</ol></article>})}</div></div></details>})}</div>
  </main>;
}
