"use client";
import Link from "next/link";
import {HistorianReport} from "@/components/historian-report";
import { FormEvent,useRef,useState,useTransition } from "react";
import { askHistorian } from "@/app/actions";
import type { HistorianContext,HistorianResponse } from "@/lib/historian";

type Message={role:"visitor"|"historian";text:string;response?:HistorianResponse};
const suggestions=["Who had the best two-year win percentage?","Who scores the most regular-season points per game?","Who won the championship in 2021?","What is Foz's career record?"];
export function HistorianChat(){
  const [messages,setMessages]=useState<Message[]>([{role:"historian",text:"The JBL archive is open. Ask me for a manager record, championship, rivalry, playoff résumé, season result, or scoring extreme."}]);
  const [context,setContext]=useState<HistorianContext|undefined>();
  const [question,setQuestion]=useState(""); const [pending,startTransition]=useTransition(); const inputRef=useRef<HTMLInputElement>(null);
  const submit=(event?:FormEvent)=>{event?.preventDefault();const clean=question.trim();if(!clean||pending)return;setMessages(current=>[...current,{role:"visitor",text:clean}]);setQuestion("");startTransition(async()=>{try{const response=await askHistorian(clean,context);setContext(response.context);setMessages(current=>[...current,{role:"historian",text:response.answer,response}]);}catch{setMessages(current=>[...current,{role:"historian",text:"The archive could not complete that query. Try the question again."}]);}finally{inputRef.current?.focus();}});};
  const askSuggestion=(value:string)=>{setQuestion(value);inputRef.current?.focus();};
  return <div className="historian-console"><section className="historian-log" aria-live="polite">{messages.map((message,index)=><article className={`historian-message ${message.role}`} key={`${message.role}-${index}`}><span>{message.role==="historian"?"JBL Historian":"You"}</span><p>{message.text}</p>{message.response?.interpretation&&<small className="historian-interpretation">Interpreted as: {message.response.interpretation}</small>}{message.response?.table&&<div className="historian-table-wrap" role="region" aria-label={message.response.table.caption} tabIndex={0}><table className="historian-table"><caption>{message.response.table.caption}</caption><thead><tr>{message.response.table.columns.map((column,i)=><th scope="col" key={i}>{column}</th>)}</tr></thead><tbody>{message.response.table.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>j===0?<th scope="row" key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}{message.response?.notes?.length?<ul>{message.response.notes.map(note=><li key={note}>{note}</li>)}</ul>:null}{!message.response?.table&&message.response?.facts.length?<ul>{message.response.facts.map(fact=><li key={fact}>{fact}</li>)}</ul>:null}{message.response?.href&&<Link href={message.response.href}>{message.response.hrefLabel} →</Link>}{message.response&&index>0&&<HistorianReport question={messages[index-1]?.text??""} response={message.response}/>}</article>)}{pending&&<article className="historian-message historian"><span>JBL Historian</span><p className="historian-thinking">Checking the official record…</p></article>}</section>
    <div className="historian-suggestions"><button type="button" disabled={pending} onClick={()=>{setContext(undefined);setQuestion("");}}>New topic</button>{suggestions.map(suggestion=><button onClick={()=>askSuggestion(suggestion)} type="button" key={suggestion}>{suggestion}</button>)}</div>
    <form className="historian-form" onSubmit={submit}><label htmlFor="historian-question">Ask the archive</label><div><input ref={inputRef} id="historian-question" value={question} onChange={event=>setQuestion(event.target.value)} maxLength={240} placeholder="e.g. What is Jack V's playoff record?" disabled={pending}/><button type="submit" disabled={pending||!question.trim()}>Ask</button></div><small>Answers use only preserved JBL statistics. The historian will not estimate missing records.</small></form>
  </div>;
}
